[build]
target = "./x86_64_foundos_target.json"
rustflags = ["-C", "relocation-model=static","--emit","obj"]

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]